// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookCityAfter.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20190505073705_201905051536")]
    partial class _201905051536
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Personnels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatTime");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("GroupId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LastLoginTime");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isEnable");

                    b.Property<int>("sex");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.ToTable("CF_Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
