// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookCityAfter.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20190429092147_201904291721")]
    partial class _201904291721
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Personnels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AliaName")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatTime");

                    b.Property<string>("Email");

                    b.Property<bool>("Enable");

                    b.Property<string>("GroupId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastLoginIP");

                    b.Property<DateTime>("LastLoginTime");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("sex");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.ToTable("personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
